function renderInternalBannerImage(){document.querySelectorAll('.page-banner').forEach(banner=>{if(banner.querySelector('.banner-image'))return;const image=document.createElement('img');image.className='banner-image';const title=banner.querySelector('h1')?.textContent.trim();image.src=title==='HOMBRE'?'https://www.figma.com/api/mcp/asset/3d2a7fdd-cada-4bcd-9894-427d1153ced1.png':title==='CAMISETAS OVERSIZE'?'https://www.figma.com/api/mcp/asset/03effb12-800c-4a61-b912-5f9be3c3e726.png':title==='FACTURA Y FEEDBACK'||title==='CARRITO DE COMPRAS'?'https://www.figma.com/api/mcp/asset/41720044-0188-4125-ab88-5fa31352a6ab.png':'https://www.figma.com/api/mcp/asset/3669a830-29c9-4559-8289-fa7973ccbbb7.png';image.alt='';banner.prepend(image)})}
document.addEventListener('DOMContentLoaded',renderInternalBannerImage);
document.addEventListener('DOMContentLoaded',renderViewIcons);
function renderViewIcons(){document.querySelectorAll('.view-icons').forEach(container=>{container.innerHTML='<svg viewBox="0 0 24 24" aria-label="Vista de cuadrícula"><rect x="4" y="4" width="5" height="5" rx=".5"/><rect x="15" y="4" width="5" height="5" rx=".5"/><rect x="4" y="15" width="5" height="5" rx=".5"/><rect x="15" y="15" width="5" height="5" rx=".5"/></svg><svg viewBox="0 0 24 24" aria-label="Vista de lista"><path d="M8 6h12M8 12h12M8 18h12"/><path d="M4 6h.01M4 12h.01M4 18h.01"/></svg>'})}
const ASSETS={hero:'https://www.figma.com/api/mcp/asset/3580514c-d41a-428c-92a4-3ebf1d80e30e.png',green:'https://www.figma.com/api/mcp/asset/467874e9-3bec-4ca2-ab7d-57b7b1424498.png',windbreaker:'https://www.figma.com/api/mcp/asset/ce45ed99-3b33-439f-8089-ed0f44a17b67.png',brown:'https://www.figma.com/api/mcp/asset/e42c0d7a-1e4d-447d-b828-ed0df0ee39a8.png',shorts:'https://www.figma.com/api/mcp/asset/6cdd8152-9934-43c7-84e9-33a0dc81fde5.png',pants:'https://www.figma.com/api/mcp/asset/33ac37b8-2c54-462e-80c9-a2292ee8e294.png',beanie:'https://www.figma.com/api/mcp/asset/42315a75-5c14-4a16-8e7e-b0b3b762e919.png'};
const PRODUCTS=[{id:'windbreaker',name:'Nike Windbreaker',price:50,image:ASSETS.windbreaker},{id:'brown-polo',name:'Polo Oversize Marrón',price:20,image:ASSETS.brown},{id:'shorts',name:'Bermuda de Felpa',price:20,image:ASSETS.shorts},{id:'wide-leg',name:'Pantalón Wide-Leg',price:35,image:ASSETS.pants},{id:'beanie',name:'Gorro cuff gris',price:15,image:ASSETS.beanie},{id:'green-shirt',name:'Camiseta Oversize Verde',price:25,image:ASSETS.green}];
const MEN_PRODUCTS=[{id:'windbreaker',name:'Nike Windbreaker',price:50,image:'https://www.figma.com/api/mcp/asset/5f277386-f194-4230-8ed0-dde52b477b0f.png'},{id:'brown-polo',name:'Polo Oversize Marrón',price:20,image:'https://www.figma.com/api/mcp/asset/afdfc41f-e745-4c6a-949d-f74e0d37cdee.png'},{id:'shorts',name:'Bermuda de Felpa',price:20,image:'https://www.figma.com/api/mcp/asset/915b5340-de56-4ec2-8def-dff1b1e490ae.png'},{id:'wide-leg',name:'Pantalón Wide-Leg',price:35,image:'https://www.figma.com/api/mcp/asset/3165740d-cf78-4275-8f8f-5df54e3ff880.png'}];
const SHIRT_PRODUCTS=[
	{id:'shirt-01',name:'Camiseta Oversize Negra',price:25,image:'https://www.figma.com/api/mcp/asset/4fb71c4d-b9cf-4909-83c7-188445608999.png'},
	{id:'shirt-02',name:'Camiseta Oversize Negra',price:25,image:'https://www.figma.com/api/mcp/asset/bd8feba0-474b-4d35-bf35-50652e4d04f9.png'},
	{id:'shirt-03',name:'Camiseta Oversize Negra',price:25,image:'https://www.figma.com/api/mcp/asset/5ac13733-d235-4a31-a9f1-7f7ad2623ba0.png'},
	{id:'shirt-04',name:'Camiseta Oversize Negra',price:25,image:'https://www.figma.com/api/mcp/asset/6223b4f8-8ab3-4a92-a925-d99f4672de2c.png'},
	{id:'shirt-05',name:'Camiseta Oversize Verde',price:25,image:'https://www.figma.com/api/mcp/asset/9f961e11-0a33-4253-880d-85d0650c3cba.png'},
	{id:'shirt-06',name:'Camiseta Oversize Beige',price:25,image:'https://www.figma.com/api/mcp/asset/7bee8036-4bca-494d-824e-a444bbfc860b.png'},
	{id:'shirt-07',name:'Camiseta Oversize Roja',price:25,image:'https://www.figma.com/api/mcp/asset/773efb67-1ecf-4d20-9e02-23a2e60a4f07.png'},
	{id:'shirt-08',name:'Camiseta Oversize Gris',price:25,image:'https://www.figma.com/api/mcp/asset/57b042fd-7d74-4f00-bce7-d88923206faf.png'},
	{id:'shirt-09',name:'Camiseta Oversize Negra',price:25,image:'https://www.figma.com/api/mcp/asset/8cc2dfff-ff1c-46f7-ad40-34edadeaed8f.png'},
	{id:'shirt-10',name:'Camiseta Oversize Blanca',price:25,image:'https://www.figma.com/api/mcp/asset/f77e8057-9916-4f7f-a6f0-60a2fbba7552.png'},
	{id:'shirt-11',name:'Camiseta Oversize Gris',price:25,image:'https://www.figma.com/api/mcp/asset/446fd812-d258-41e7-9d8e-e33d46d2c0f2.png'},
	{id:'shirt-12',name:'Camiseta Oversize Blanca',price:25,image:'https://www.figma.com/api/mcp/asset/bfaa782d-4283-495e-a819-a32a5ea08c2a.png'}
];
function header(){return `<header class="site-header"><a class="brand" href="index.html"><strong>DISTRICT</strong><small>URBAN EMPIRE</small></a><nav><a href="index.html">INICIO</a><a href="hombres.html">HOMBRES</a><a href="hombres.html">PROMOCIONES</a><a href="hombres.html">SERVICIOS</a></nav><div class="actions"><button aria-label="Buscar"><svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="20" cy="20" r="11"/><path d="M28 28l10 10"/></svg></button><a aria-label="Mi cuenta" href="#"><svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="15" r="7"/><path d="M10 41c0-8 5.7-13 14-13s14 5 14 13"/></svg></a><a aria-label="Carrito" href="carrito.html"><svg viewBox="0 0 48 48" aria-hidden="true"><path d="M5 8h6l4 24h23l5-17H14"/><circle cx="19" cy="40" r="2.5"/><circle cx="35" cy="40" r="2.5"/></svg><span class="cart-count">${cart().reduce((a,p)=>a+p.qty,0)}</span></a></div></header>`}
function footer(){return `<footer class="site-footer"><div class="newsletter"><img class="newsletter-icon" src="https://www.figma.com/api/mcp/asset/db85dac8-9863-4eb8-b3b7-eb58add4e667.svg" alt=""><div class="newsletter-copy"><b>SE EL PRIMERO EN ENTERARTE</b><small>Suscribete y recibe noticias de lanzamientos,<br>ofertas exclusivas y mas.</small></div><form><input type="email" placeholder="Ingresa tu correo electronico"><button>SUSCRIBIRME</button></form></div><div class="footer-main"><div class="footer-brand">DISTRICT.<small>URBAN EMPIRE</small><div class="footer-social"><img src="https://www.figma.com/api/mcp/asset/c14aa1a9-5c67-4f9f-bc7b-9390a39fdf5f.svg" alt="Facebook"><img src="https://www.figma.com/api/mcp/asset/bf7cc6c6-a1a5-4b4c-b31e-77a00a275cb8.svg" alt="Twitter"><img src="https://www.figma.com/api/mcp/asset/65e70907-a88f-4dc9-8891-6890e4d89c1b.svg" alt="Instagram"><img src="https://www.figma.com/api/mcp/asset/c93d2bce-e85c-4d5b-b267-9dd0de5072fb.svg" alt="LinkedIn"></div></div><div><h3>TIENDA</h3><p>Inicio<br>Hombre<br>Promociones<br>Accesorios</p></div><div><h3>SERVICIOS</h3><p>Probador virtual<br>Guia de tallas<br>Cambios y devoluciones</p></div><div class="footer-about"><h3>NOSOTROS</h3><p>Trabaja con nosotros<br>Contacto<br>Blog</p><img class="footer-payments" src="https://www.figma.com/api/mcp/asset/1e3aa2c4-2d71-4bdc-a642-428134e253e5.svg" alt="Medios de pago"></div><div class="copyright">© 2026 Urban Empire. Todos los derechos reservados.</div></div></footer>`}
function cart(){return JSON.parse(localStorage.getItem('district-cart')||'[]')}
function saveCart(value){localStorage.setItem('district-cart',JSON.stringify(value))}
function productCard(p){return `<article class="product-card"><a href="producto.html"><img src="${p.image}" alt="${p.name}"></a><span class="heart">♡</span><div class="card-copy"><strong>${p.name}</strong><span>$ ${p.price.toFixed(2)}</span></div></article>`}
function renderProducts(){document.querySelectorAll('[data-products]').forEach(container=>{let list=PRODUCTS;if(container.dataset.products==='new')list=PRODUCTS.slice(0,5);if(container.dataset.products==='men')list=Array.from({length:3},()=>MEN_PRODUCTS).flat();if(container.dataset.products==='shirts')list=SHIRT_PRODUCTS;if(container.dataset.products==='recommendations')list=PRODUCTS.slice(2,4).concat(PRODUCTS.slice(2,4));container.innerHTML=list.concat(container.dataset.products==='catalog'?PRODUCTS.slice(0,3):[]).map(productCard).join('')})}
function renderCart(){const target=document.querySelector('#cart-items');if(!target)return;const items=cart();target.innerHTML=items.length?items.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id);return `<div class="cart-row"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><strong class="price">$${p.price.toFixed(2)}</strong><p>Talla: M<br>Color: ${p.id==='green-shirt'?'Verde':'Negro'}</p></div><div class="cart-controls"><button data-cart="minus" data-id="${p.id}">−</button> ${item.qty} <button data-cart="plus" data-id="${p.id}">+</button> <button class="remove" data-cart="remove" data-id="${p.id}">Eliminar</button></div></div>`}).join(''):'<p>Tu carrito está vacío.</p>';const subtotal=items.reduce((sum,item)=>sum+(PRODUCTS.find(p=>p.id===item.id).price*item.qty),0);document.querySelector('#cart-subtotal').textContent=`$${subtotal.toFixed(2)}`;document.querySelector('#cart-total').textContent=`$${(subtotal+3.5).toFixed(2)}`}
function renderInvoice(){const target=document.querySelector('#invoice-items');if(!target)return;const items=cart();const subtotal=items.reduce((sum,item)=>sum+PRODUCTS.find(p=>p.id===item.id).price*item.qty,0);target.innerHTML=items.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);return `<p>${i.qty}x ${p.name} — $${(p.price*i.qty).toFixed(2)}</p>`}).join('')||'<p>No hay productos.</p>';document.querySelector('#invoice-subtotal').textContent=`$${subtotal.toFixed(2)}`;document.querySelector('#invoice-total').textContent=`$${(subtotal+3.5).toFixed(2)}`}
document.addEventListener('DOMContentLoaded',()=>{if(document.querySelector('#site-header'))document.querySelector('#site-header').innerHTML=header();if(document.querySelector('#site-footer'))document.querySelector('#site-footer').innerHTML=footer();renderProducts();renderCart();renderInvoice();document.querySelectorAll('.add-to-cart').forEach(btn=>btn.addEventListener('click',()=>{const items=cart(),found=items.find(i=>i.id===btn.dataset.id);if(found)found.qty++;else items.push({id:btn.dataset.id,qty:1});saveCart(items);btn.textContent='AÑADIDO';setTimeout(()=>btn.textContent='AÑADIR AL CARRITO',1200)}));document.addEventListener('click',e=>{if(!e.target.dataset.cart)return;const items=cart(),item=items.find(i=>i.id===e.target.dataset.id);if(e.target.dataset.cart==='plus')item.qty++;if(e.target.dataset.cart==='minus')item.qty=Math.max(1,item.qty-1);if(e.target.dataset.cart==='remove')items.splice(items.indexOf(item),1);saveCart(items);renderCart();renderInvoice()});document.querySelector('#checkout-form')?.addEventListener('submit',e=>{e.preventDefault();alert('Pago confirmado. ¡Gracias por comprar en District.!')})});